#!/bin/bash

# build: a script for building the OME plugin for ImageJ JAR file

cd ../../..

echo Building ome_plugin.jar...
cp loci/ome/ij/ome.manifest loci/ome/ij/plugins.config .
echo OME plugin for ImageJ > about.txt
echo Built `date` >> about.txt
echo >> about.txt
echo The OME plugin for ImageJ is LOCI software written >> about.txt
echo by Phil Huettl, Melissa Linkert and Curtis Rueden. >> about.txt
echo >> about.txt
echo http://www.loci.wisc.edu/ome/imagej.html >> about.txt
mv about.txt loci/util/about.txt
jar cfm loci/ome/ij/ome_plugin.jar ome.manifest \
plugins.config loci/util/about.txt \
loci/ome/ij/*.class loci/ome/*.class loci/ome/viewer/*.class \
loci/util/*.class loci/browser/*.class \
loci/ome/ij/*.java loci/ome/*.java loci/ome/viewer/*.java \
loci/util/*.java loci/browser/*.java \
loci/ome/ij/build loci/ome/ij/plugins.config loci/ome/ij/ome.manifest
rm ome.manifest plugins.config loci/util/about.txt

cd loci/ome/ij
ls -l ome_plugin.jar
