#!/bin/sh

# LOCI Bio-Formats package for reading and converting biological file formats.
# Copyright (C) 2005-2006 Melissa Linkert, Curtis Rueden and Eric Kjellman.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# build: a script for building the LOCI Bio-Formats plugin for ImageJ

cd ../..

# build bio_formats_src.jar
jar cvfM loci/formats/bio_formats_src.jar loci/formats/plugins.config loci/formats/*.java loci/formats/*.txt loci/formats/test loci/formats/build

# build bio_formats.jar
mv loci/formats/plugins.config loci/formats/LociPlugin.class .
jar cvfM loci/formats/bio_formats.jar plugins.config LociPlugin.class loci/formats/readers.txt loci/formats/writers.txt loci/formats/*.class
mv plugins.config LociPlugin.class loci/formats

cd loci/formats
ls -l *.jar
cp bio_formats.jar ~/Desktop/ImageJ/plugins/
