#!/bin/sh

# LOCI Bio-Formats package for reading and converting biological file formats.
# Copyright (C) 2005-2006 Melissa Linkert, Curtis Rueden and Eric Kjellman.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# build: a script for building the LOCI Bio-Formats JAR file

cd ../..

echo Building bio_formats.jar...
cp loci/formats/formats.manifest loci/formats/plugins.config .
echo LOCI Bio-Formats > about.txt
echo Built `date` >> about.txt
echo >> about.txt
echo The LOCI Bio-Formats package is LOCI software written >> about.txt
echo by Melissa Linkert, Curtis Rueden and Eric Kjellman. >> about.txt
echo >> about.txt
echo http://www.loci.wisc.edu/ome/formats.html >> about.txt
mv about.txt loci/util/about.txt
jar cfm loci/formats/bio_formats.jar formats.manifest \
plugins.config loci/util/about.txt \
loci/formats/*.class loci/util/About*.class loci/formats/*.txt \
loci/formats/*.java loci/util/About*.java loci/formats/test \
loci/formats/build loci/formats/plugins.config loci/formats/formats.manifest
rm formats.manifest plugins.config loci/util/about.txt

cd loci/formats
ls -l bio_formats.jar
