#!/bin/sh

# build: a script for building the LeicaConverter JAR file

cd ../..

echo Building LeicaConverter.jar...
cp loci/leica/leica.manifest .
jar cfm loci/leica/LeicaConverter.jar \
leica.manifest loci/leica/*.class \
loci/leica/*.java loci/leica/build \
loci/formats/*.class loci/formats/*.txt \
loci/formats/*.java loci/formats/test loci/formats/build \
loci/formats/plugins.config loci/formats/formats.manifest \
-C ../OME-JAVA/src org/openmicroscopy/ds \
-C ../OME-JAVA/src org/openmicroscopy/xml
rm leica.manifest

cd loci/leica
ls -l LeicaConverter.jar
