#!/bin/sh

# build: a script for building the OME Metadata Viewer JAR file

cd ../../..

echo Building MetadataViewer.jar...
cp loci/ome/viewer/viewer.manifest .
echo OME Metadata Viewer > about.txt
echo Built `date` >> about.txt
echo >> about.txt
echo The OME Metadata Viewer is LOCI software >> about.txt
echo written by Curtis Rueden. >> about.txt
echo >> about.txt
echo 'http://www.loci.wisc.edu/4d/#metadata' >> about.txt
mv about.txt loci/util/about.txt
jar cfm loci/ome/viewer/MetadataViewer.jar viewer.manifest \
loci/util/about.txt \
loci/ome/viewer/*.class loci/ome/*.class loci/util/*.class \
loci/ome/viewer/*.java loci/ome/*.java loci/util/*.java \
loci/ome/viewer/build loci/ome/viewer/viewer.manifest \
-C ../OME-JAVA/src org/openmicroscopy/ds \
-C ../OME-JAVA/src org/openmicroscopy/xml
rm viewer.manifest loci/util/about.txt

cd loci/ome/viewer
ls -l MetadataViewer.jar
