#!/bin/sh

# build: a script for building the SlimPlotter JAR file

cd ../..
ln -s /home/curtis/cvs/VisAD/visad

echo Building SlimPlotter.jar...
cp loci/slim/slim.manifest .
jar cfm loci/slim/SlimPlotter.jar \
slim.manifest loci/slim/*.class \
loci/formats/DataTools*.class \
loci/formats/ExtensionFileFilter*.class loci/formats/ComboFileFilter*.class \
loci/visbio/util/OutputConsole*.class loci/visbio/util/OutputEvent*.class \
loci/visbio/util/SwingUtil*.class loci/visbio/util/LAFUtil*.class \
visad/*.class visad/java3d/*.class visad/java2d/MouseBehaviorJ2D*.class \
visad/browser/Divider*.class visad/browser/RangeSlider*.class \
visad/browser/Convert*.class \
visad/util/*.class visad/collab/*.class \
visad/data/*.class visad/data/units/*.class \
visad/bom/CurveManipulationRendererJ3D*.class \
visad/bom/ShadowCurveSetTypeJ3D*.class \
loci/slim/*.java loci/slim/build
rm slim.manifest

rm visad
cd loci/slim
ls -l SlimPlotter.jar
