#!/bin/sh

set -e

root=published
current=$(ls -1d Released-Schema/20* | sort)
current=${current/*\//}

# Clean up

rm -rf "$root"
mkdir -p "$root"

for dir in Released-Schema/20*
do
    # Don't copy legacy or other material
    if [ "$dir" = "Released-Schema/additions" ]; then
	continue
    fi

    for schema in "$dir"/*.xsd
    do
	rel=${dir/*\//}
	base=${schema%.xsd}
	base=${base/*\//}
	name=${schema/*\//}
	type="legacy"
	version=$(grep "version=" "$schema" | grep -v 'xml' | head -n1 | sed -e 's;^.*version="\([0-9][0-9]*\)".*$;\1;')

	year=${rel/-*}
	month=${rel/*-}

	# Skip files only used internally for legacy schema
	if [ "$rel" = "2003-FC" ] && [ "$base" != "ome" ]; then
	    continue;
	fi

	# For some reason, the OME schema has always been lowercased
	if [ "$base" = "ome" ]; then
	    base="OME"
	fi

	if [ "$rel" = "$current" ]; then
	    type="current"
	fi

	if [ -z "$version" ]; then
	    version=1
	fi

	# Special case copying of legacy schemas
	if [ "$year" = "2003" ]; then
	    path="${root}/XMLschemas/${base}/${month}"
	    reldate="2003 ($month)"
	else
	    path="${root}/Schemas/${base}/${rel}"
	    reldate=$(date -jnu -f "%Y-%m" "$rel" '+%B %Y')
	fi

	# Copy schema
	mkdir -p "$path"
	cp -v "$schema" "${path}/${name}"

	# Generate companion HTML index.html
	echo "HTML -> ${path}/index.html"
	cat <<EOF > "${path}/index.html"
<?xml version='1.0'?>
<!DOCTYPE html PUBLIC "-//XML-DEV//DTD XHTML RDDL 1.0//EN" "http://www.w3.org/2001/rddl/rddl-xhtml.dtd" >
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:rddl="http://www.rddl.org/" xml:lang="en">
<head>
        <title>Open Microscopy Environment ${base} Schema</title>
</head>
<body>
<h1>Open Microscopy Environment OME Schema</h1>
<div class="head">
<p>${reldate}</p>
</div>
<div id="toc">
<h2>Table of contents</h2>
	<ol>
		<li><a href="#intro">Introduction</a></li>
		<li><a href="#status">Status</a></li>
		<li><a href="#schema">Schema</a></li>
	</ol>
</div>
<div id="intro">
<h2>Introduction</h2>
<p>This document outlines the ${base} Schema created by the Open Microscopy Environment Group. Detailed information on the schema and future development plans are available at <a href="http://www.openmicroscopy.org/site/support/file-formats">http://www.openmicroscopy.org/site/support/file-formats</a>. Further information on the groups work is available at <a href="http://www.openmicroscopy.org/">http://www.openmicroscopy.org/</a>
</p>
</div>
<div id="status">
<h2>Status</h2>
<p>This schema is <strong>${type}</strong> and at version <strong>${version}</strong>.</p>
<p>A list of the current versions of all the Open Microscopy Environment Group schemas is available at <a href="http://www.openmicroscopy.org/Schemas/">http://www.openmicroscopy.org/Schemas/</a></p>
</div>
<div id="schema">
<h2>Schema</h2>
<p>The schema XSD file is <a href="${name}">${name}</a>.</p>
<p>Note: Some browsers will try to render XSD files when you view them. This can result in either a blank screen or unformatted text. Choose to either download the file or view the source.</p>
</div>
<hr/>
</body>
</html>
EOF
    done
done

# Special cases

path="${root}/Schemas/Styling/2009-09"
mkdir -p "$path"
cp -rv Released-Schema/2009-09/display* Released-Schema/2009-09/jquery.js Released-Schema/2009-09/index.html "$path"
cp -v Released-Schema/2009-09/index.html "${root}/Schemas/Styling"