#!/bin/sh

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# Copyright (C) 2013 - 2016 Open Microscopy Environment
#       Massachusetts Institute of Technology,
#       National Institutes of Health,
#       University of Dundee,
#       University of Wisconsin at Madison
#
# This work is licensed under the
#       Creative Commons Attribution 3.0 Unported License.
# To view a copy of this license, visit
#       http://creativecommons.org/licenses/by/3.0/
# or send a letter to
#       Creative Commons, 444 Castro Street, Suite 900,
#       Mountain View, California, 94041, USA.
# For attribution instructions, visit
#       http://www.openmicroscopy.org/info/attribution
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

set -e

XARGSOPTS=
xargs -r </dev/null 2>/dev/null >/dev/null && XARGSOPTS="-r"

# Parse date from a YYYY-MM string
parsedate() {
    if date -j 2>/dev/null >/dev/null; then
        echo $(date -jnu -f "%Y-%m" "$1" '+%B %Y')
    else
        echo $(date -d "${1}-01" '+%B %Y')
    fi
}

curdate() {
    date '+%B %Y'
}

# Get the most recent version of a schema
# $1=schema name
mostrecentversion() {
    echo "$(basename $(dirname $(find released-schema -name "$1" | grep -v $devmarker | sort | tail -n1)))"
}

# Check if the a schema is the most recent version (return true) or legacy (return false)
# $1=schema name
# $2=release to check if current
ismostrecent() {
    if [ "$2" != "$(mostrecentversion "$1")" ]; then
        return 1
    fi

    return 0
}

# Check if a schema is current (not necessarily the latest version).
# $1=schema name
iscurrent() {
    if [ "${1%.xsd}" = "AnalysisChain" ] || \
        [ "${1%.xsd}" = "AnalysisModule" ] || \
        [ "${1%.xsd}" = "CA" ] || \
        [ "${1%.xsd}" = "CLI" ] || \
        [ "${1%.xsd}" = "DataHistory" ] || \
        [ "${1%.xsd}" = "Editor" ] || \
        [ "${1%.xsd}" = "MLI" ] || \
        [ "${1%.xsd}" = "OMERO" ] || \
        [ "${1%.xsd}" = "STD" ]
    then
        return 1
    fi

    return 0
}

# Check if the a schema is the most recent version (return true) or legacy (return false)
# $1=schema name
# $2=release to check if current
schemastatus() {
    if iscurrent "$1"; then
        if ismostrecent "$1" "$2"; then
            echo "currently in use (and is the most recent release)"
        else
            echo "currently in use (but superseded by a more recent release)"
        fi
    else
        if ismostrecent "$1" "$2"; then
            echo "no longer in use (final release)"
        else
            echo "no longer in use (and superseded by a more recent release)"
        fi
    fi
}

# Get the version of a schema
# $1=schema name
# $2=release to check if current
schemaversion() {
        version=$(grep "version=" "released-schema/$2/$1" | grep -v 'xml' | head -n1 | sed -e 's;^.*version="\([0-9][0-9]*\)".*$;\1;')
        if [ -z "$version" ]; then
            version="1"
        fi
        echo "$version"
}

# Describe a schema (single sentence)
schemadesc() {
    case "${1%.xsd}" in
        BinaryFile)
            echo "Binary File schema used to describe a file location, or the location of a fragment within a file." ;;
        OME|ome)
            echo "main schema which defines the OME ontology for microscopy. This schema makes use of the others." ;;

        OMERO)
            echo "schema extensions used by OMERO. It is not used by the OME schema but provides a structure for data in StructuredAnnotation blocks used by OMERO." ;;
        ROI)
            echo "Region Of Interest schema." ;;
        SA)
            echo "Structured Annotation schema." ;;
        SPW)
            echo "Screen/Plate/Well schema." ;;
        AnalysisChain)
            echo "Analysis Chain schema. Analysis chains are how module outputs are connected to inputs of other modules." ;;
        AnalysisModule)
            echo "Analysis Module Library schema. Analysis modules are image analysis algorithms or, more generally, how information is generated in OME. Makes use of CLI and MLI schemas." ;;
        CA)
            echo "standard Custom Attribute schema." ;;
        CLI)
            echo "Command Line Interface sub-schema." ;;
        DataHistory)
            echo "Data History schema. Data history describes the data dependency in OME." ;;
        MLI)
            echo "Matlab Interface sub-schema." ;;
        STD)
            echo "Semantic Type definition schema. Once a Semantic Type is defined, data for the defined type can be imported into the OME server." ;;
        *)
            echo "${1%.xsd} schema." ;;
    esac
}

# from http://stackoverflow.com/questions/2829613/how-do-you-tell-if-a-string-contains-another-string-in-unix-shell-scripting
# contains(string, substring)
#
# Returns 0 if the specified string contains the specified substring,
# otherwise returns 1.
contains() {
    string="$1"
    substring="$2"
    if test "${string#*$substring}" != "$string"
    then
        return 0    # $substring is in $string
    else
        return 1    # $substring is not in $string
    fi
}

devmarker="DEV"
root=published


# Clean up

rm -rf "$root"
mkdir -p "$root"

for dir in released-schema/20*
do

    if contains $dir $devmarker; then
        echo "Skipping $dir folder"
        continue
    fi

    for schema in "$dir"/*.xsd
    do
        rel=$(basename "$dir")
        base=${schema%.xsd}
        base=$(basename "$base")
        name=$(basename "$schema")
        type="$(schemastatus "$name" "$rel")"
        version="$(schemaversion "$name" "$rel")"

        year=$(echo "$rel" | sed -e 's;^\([0-9][0-9]*\)-.*$;\1;')
        month=$(echo "$rel" | sed -e 's;^.*-\([0-9][0-9]*\)$;\1;')

        # Skip files only used internally for legacy schema
        if [ "$rel" = "2003-FC" ] && [ "$base" != "ome" ]; then
            continue;
        fi

        # For some reason, the OME schema has always been lowercased
        if [ "$base" = "ome" ]; then
            base="OME"
        fi

        if [ -z "$version" ]; then
            version=1
        fi

        # Special case copying of legacy schemas
        if [ "$year" = "2003" ]; then
            path="${root}/${base}/${month}"
            path=$(echo "$path" | sed -e 's;/2003-\(.*\);/\1;')
            reldate="2003 ($month)"
        else
            path="${root}/${base}/${rel}"
            reldate=$(parsedate "$rel")
        fi

        # Copy schema
        mkdir -p "$path"
        cp -v "$schema" "${path}/${name}"

        # Generate companion HTML index.html
        echo "HTML [1] -> ${path}/index.html"
        cat <<EOF > "${path}/index.html"
<?xml version='1.0'?>
<!DOCTYPE html PUBLIC "-//XML-DEV//DTD XHTML RDDL 1.0//EN" "http://www.w3.org/2001/rddl/rddl-xhtml.dtd" >
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:rddl="http://www.rddl.org/" xml:lang="en">
<head>
        <title>Open Microscopy Environment ${base} Schema</title>
</head>
<body>
<h1>Open Microscopy Environment OME Schema</h1>
<div class="head">
<p>${reldate}</p>
</div>
<div id="toc">
<h2>Table of contents</h2>
        <ol>
                <li><a href="#intro">Introduction</a></li>
                <li><a href="#status">Status</a></li>
                <li><a href="#schema">Schema</a></li>
        </ol>
</div>
<div id="intro">
<h2>Introduction</h2>
<p>This document outlines the ${base} Schema created by the Open Microscopy Environment Group. Detailed information on the schema and future development plans are available at <a href="http://www.openmicroscopy.org/site/support/ome-model/index.html">http://www.openmicroscopy.org/site/support/ome-model/index.html</a>. The main OME website is available at <a href="http://www.openmicroscopy.org/">http://www.openmicroscopy.org/</a>
</p>
</div>
<div id="status">
<h2>Status</h2>
<p>This schema is <strong>${type}</strong> and at version <strong>${version}</strong>.</p>
<p>A list of the current versions of all the Open Microscopy Environment Group schemas is available at <a href="http://www.openmicroscopy.org/Schemas/">http://www.openmicroscopy.org/Schemas/</a></p>
</div>
<div id="schema">
<h2>Schema</h2>
<p>The schema XSD file is <a href="${name}">${name}</a>.</p>
<p>Note: Some browsers will try to render XSD files when you view them. This can result in either a blank screen or unformatted text. Choose to either download the file or view the source.</p>
</div>
<hr/>
</body>
</html>
EOF
    done
done

# Special cases

# Transforms folder
path="${root}/Transforms/"
dir="transforms"
mkdir -p "$path"
for transform in "$dir"/*.xsl
do
    if contains $transform $devmarker; then
        echo "Skipping $transform"
        continue
    fi
    cp -v "$transform" "$path"
done

# Root index

# Create an HTML link for a schema.
# $1=schema
# $2=year (may be blank)
# $3=filter (current or legacy)
# $4=verbose (true or false)
# $5=schema set (current or legacy)
createlink() {
    name=$(basename "$1")
    release="$2"
    shortname="${name%.xsd}"
    if [ "$shortname" = "ome" ]; then
        shortname="OME"
    fi
    if [ "$5" = "legacy" ]; then
        reldate="2003 ($2)"
    else
        if [ -z "$2" ]; then
            release=$(mostrecentversion "$name")
            reldate=$(parsedate "$release")
        else
            reldate=$(parsedate "$2")
        fi
    fi
    if [ "$5" = "current" ]; then
        relversion=$(schemaversion "$name" "$release")
    else
        relversion=$(schemaversion "$name" "2003-$release")
    fi
    reldesc=" The $(schemadesc "$name")"
    if [ "$4" = "false" ]; then
        reldesc=""
    fi
    link=$(find published -name "$name" | grep "$release" | head -n1)
    link=$(echo "$link" | sed -e 's;published/;;')
    if [ -n "$2" ]; then
        link=$(echo "$link" | sed -e "s;^${shortname}/;;")
    fi
    if [ -z "$2" ]; then
        line="<li><a href=\"${shortname}/index.html\">${shortname}</a> - $reldate, version ${relversion} [<a href=\"${link}\">${name}</a>]${reldesc}</li>"
    else
        line="<li><a href=\"$2/index.html\">$2</a> - $reldate, version ${relversion} [<a href=\"${link}\">${name}</a>] ${reldesc}</li>"
    fi
    if [ -z "$2" ]; then
        if iscurrent "$name" && [ "$3" = "current" ]; then
            echo "$line"
        elif ! iscurrent "$name" && [ "$3" != "current" ]; then
            echo "$line"
        fi
    else
        if ismostrecent "$name" "$2" && [ "$3" = "current" ]; then
            echo "$line"
        elif ! ismostrecent "$name" "$2" && [ "$3" != "current" ]; then
            echo "$line"
        fi
    fi
}

# Create main HTML index page

createmainindex() {
    cat <<EOF
<?xml version='1.0'?>
<!DOCTYPE html PUBLIC "-//XML-DEV//DTD XHTML RDDL 1.0//EN" "http://www.w3.org/2001/rddl/rddl-xhtml.dtd" >
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:rddl="http://www.rddl.org/" xml:lang="en">
<head>
        <title>Open Microscopy Environment Schemas</title>
</head>
<body>
<h1>Open Microscopy Environment Schemas</h1>
<div class="head">
<p>$(curdate)</p>
</div>
<div id="toc">
<h2>Table of contents</h2>
        <ol>
                <li><a href="#intro">Introduction</a></li>
                <li><a href="#schema.list">Schemas</a></li>
                <li><a href="#history">History</a></li>
        </ol>
</div>
<div id="intro">
<h2>Introduction</h2>
<p>This document outlines the XML Schemas created by the Open Microscopy Environment Group. Detailed information on the schemas and future development plans are available at <a href="http://www.openmicroscopy.org/site/support/ome-model/index.html">http://www.openmicroscopy.org/site/support/ome-model/index.html</a>. The main OME website is available at <a href="http://www.openmicroscopy.org/">http://www.openmicroscopy.org/</a>
</p>
<p>Auto generated documentation for the schemas is available at: <a href="http://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2015-01/ome.html">http://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2015-01/ome.html</a></a>
</p>
</div>
EOF

    cat <<EOF
<div id="schema.list">
<h2>Schemas</h2>
<p>This has the schema name, the current version, a link to the XSD file, and a short description</p>
<p><em>Note: Some browsers will try to render XSD files when you view them. This can result in either a blank screen or unformatted text. Choose to either download the file or view the source.</em></p>
<h4>Active Schemas</h4>
<ul>
EOF

    for schema in $(find published -name '*xsd' | xargs $XARGSOPTS -n1 basename | sort | uniq ); do
        createlink "$schema" "" "current" "true" "current" "$1"
    done

    cat <<EOF
</ul>
<h4>Legacy Schemas</h4>
<ul>
EOF

    for schema in $(find published -name '*xsd' | xargs $XARGSOPTS -n1 basename | sort | uniq); do
        createlink "$schema" "" "legacy" "true" "current" "$1"
    done
    cat <<EOF
</ul>
</div>
<div id="history">
<h2>History</h2>
<p>This lists the most recent version of past schemas. The schemas are in a process of constant development to extend and refine the OME Data Model. See the
<a href="https://www.openmicroscopy.org/site/support/ome-model/schemas/index.html">Schema version history</a> for more information.
</p>
<ul>
EOF

    for release in $(ls -1d released-schema/20* | grep -v 2003 | grep -v $devmarker | xargs $XARGSOPTS -n1 basename | sort -r); do
        reldate=$(parsedate "$release")
        echo "<li>$reldate - namespace /$release/</li>"
    done
    for release in $(ls -1d released-schema/20* | grep 2003 | xargs $XARGSOPTS -n1 basename | sort -r | grep FC | sed -e 's;2003-\(.*\);\1;') $(ls -1d released-schema/20* | grep 2003 | xargs $XARGSOPTS -n1 basename | sort -r | grep -v FC | sed -e 's;2003-\(.*\);\1;'); do
        reldate="2003 ($release)"
        echo "<li>$reldate - namespace /$release/*.xsd</li>"
    done

    cat <<EOF
</ul>
</div>
<hr/>
</body>
</html>
EOF
}

createintermediateindex() {
    current="This schema is currently used."
    if ! iscurrent "$1"; then
        current="This schema is no longer in use."
    fi
    schema="$1.xsd"
    if [ "$1" = "OME" ]; then
        schema="ome.xsd"
    fi

    cat <<EOF
<?xml version='1.0'?>
<!DOCTYPE html PUBLIC "-//XML-DEV//DTD XHTML RDDL 1.0//EN" "http://www.w3.org/2001/rddl/rddl-xhtml.dtd" >
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:rddl="http://www.rddl.org/" xml:lang="en">
<head>
        <title>Open Microscopy Environment $1 Schemas</title>
</head>
<body>
<h1>Open Microscopy Environment $1 Schemas</h1>
<div class="head">
<p>$(curdate)</p>
</div>
<div id="toc">
<h2>Table of contents</h2>
        <ol>
                <li><a href="#intro">Introduction</a></li>
                <li><a href="#schema.list">Schemas</a></li>
                <li><a href="#history">History</a></li>
        </ol>
</div>
<div id="intro">
<h2>Introduction</h2>
<p>This document outlines the XML $1 Schemas created by the Open Microscopy Environment Group. This is the $(schemadesc "$1")  Detailed information on the schemas and future development plans are available at <a href="http://www.openmicroscopy.org/site/support/ome-model/index.html">http://www.openmicroscopy.org/site/support/ome-model/index.html</a>. The main OME website is available at <a href="http://www.openmicroscopy.org/">http://www.openmicroscopy.org/</a>
</p>
</div>
EOF

    cat <<EOF
<div id="schema.list">
<h2>Schemas</h2>
<p>This has the schema name, the current version, a link to the XSD file, and a short description</p>
<p><em>Note: Some browsers will try to render XSD files when you view them. This can result in either a blank screen or unformatted text. Choose to either download the file or view the source.</em></p>
<p><b>$current</b></p>
<h4>Most recent schema</h4>
<ul>
EOF

    for year in $(find published -name "$schema" | xargs $XARGSOPTS -n1 dirname | xargs $XARGSOPTS -n1 basename | grep -v $devmarker | grep -v html | grep 20 | sort -r); do
        createlink "$schema" "$year" "current" "false" "current"
    done
    for year in $(find published -name "$schema" | grep 2003 | xargs $XARGSOPTS -n1 dirname | xargs $XARGSOPTS -n1 basename | grep -v $devmarker | grep -v html | sort -r | grep FC) $(find published -name "$schema" | xargs $XARGSOPTS -n1 dirname | xargs $XARGSOPTS -n1 basename | grep -v $devmarker | grep -v html | sort -r | grep -v 20 | grep -v FC); do
        createlink "$schema" "$year" "current" "false" "legacy"
    done

    cat <<EOF
</ul>
<h4>Older schemas</h4>
<ul>
EOF

    for year in $(find published -name "$schema" | xargs $XARGSOPTS -n1 dirname | xargs $XARGSOPTS -n1 basename | grep -v $devmarker | grep -v html | grep 20 | sort -r); do
        createlink "$schema" "$year" "legacy" "false" "current"
    done
    for year in $(find published -name "$schema" | xargs $XARGSOPTS -n1 dirname | xargs $XARGSOPTS -n1 basename | grep -v $devmarker | grep -v html | sort -r | grep FC) $(find published -name "$schema" | xargs $XARGSOPTS -n1 dirname | xargs $XARGSOPTS -n1 basename | grep -v $devmarker | grep -v html | sort -r | grep -v 20 | grep -v FC); do
        createlink "$schema" "$year" "legacy" "false" "legacy"
    done

    cat <<EOF
</ul>
</div>
<div id="history">
<h2>History</h2>
<p>This lists the current and prior versions of the $1 schema. The schemas are in a process of constant development to extend and refine the OME Data Model. See the
<a href="https://www.openmicroscopy.org/site/support/ome-model/schemas/index.html">Schema version history</a> for more information.
</p>
<ul>
EOF

    for release in $(ls -1d "$root"/$1/20* | xargs $XARGSOPTS -n1 basename | grep -v $devmarker | grep -v html | sort -r ); do
        reldate=$(parsedate "$release")
        echo "<li>$reldate - namespace /$release/</li>"
    done
    for release in $(ls -1d "$root"/$1/* | xargs $XARGSOPTS -n1 basename | grep -v $devmarker | grep -v html  | sort -r | grep FC) $(ls -1d "$root"/$1/* | xargs $XARGSOPTS -n1 basename | grep -v $devmarker | grep -v html | sort -r | grep -v 20 | grep -v FC); do
        reldate="2003 ($release)"
        echo "<li>$reldate - namespace /$release/$schema</li>"
    done


    cat <<EOF
</ul>
</div>
<hr/>
</body>
</html>
EOF
}

for type in $(find "${root}" -mindepth 1 -maxdepth 1 -type d | sed -e 's;^published/;;'); do
    if [ $type != "Transforms" ]; then
        echo "HTML [2] -> $root/${type}/index.html"
        createintermediateindex "$type" > "$root/${type}/index.html"
    fi
done


echo "HTML [4] -> ${root}/index.html"
createmainindex "current" > "${root}/index.html"
