#!/bin/sh

# build: a script for building the SlimPlotter JAR file

cd ../..

echo Building SlimPlotter.jar...
cp loci/slim/slim.manifest .
jar cfm loci/slim/SlimPlotter.jar \
slim.manifest loci/slim/*.class \
loci/formats/DataTools.class \
loci/formats/ExtensionFileFilter.class loci/formats/ComboFileFilter.class \
visad/*.class visad/java3d/*.class visad/java2d/*.class \
visad/browser/*.class visad/util/*.class visad/collab/*.class \
visad/data/*.class visad/data/units/*.class \
loci/slim/*.java loci/slim/build
rm slim.manifest

cd loci/slim
ls -l SlimPlotter.jar
