
#
# In order to provide default implementations of the Overridable
# methods, you can put this module in a location where it can be
# imported when your code (generated by generateDS.py) is run. 
# Then modify the implementation (but *not* the names or signature)
# of methods to suit your purposes.


class GeneratedsSuper:
    def format_string(self, input_data, input_name=''):
        return input_data
    def format_integer(self, input_data, input_name=''):
        return '%d' % input_data
    def format_float(self, input_data, input_name=''):
        return '%f' % input_data
    def format_double(self, input_data, input_name=''):
        return '%e' % input_data
    def format_boolean(self, input_data, input_name=''):
        return '%s' % input_data


