#!/bin/sh

# build: a script for building the OME Metadata Notebook JAR file

cd ../../..

echo Building MetadataNotebook.jar...
cp loci/ome/notebook/notebook.manifest .
echo OME Metadata Notebook > about.txt
echo Built `date` >> about.txt
echo >> about.txt
echo The OME Metadata Notebook is LOCI software >> about.txt
echo written by Christopher Peterson. >> about.txt
echo >> about.txt
echo 'http://www.loci.wisc.edu/4d/#metadata' >> about.txt
mv about.txt loci/util/about.txt
jar cfm loci/ome/notebook/MetadataNotebook.jar notebook.manifest \
loci/util/about.txt \
loci/ome/notebook/*.class loci/ome/*.class loci/util/*.class \
loci/ome/notebook/*.java loci/ome/*.java loci/util/*.java \
loci/ome/notebook/build loci/ome/notebook/notebook.manifest \
loci/formats/DataTools.class loci/formats/FormatException.class \
loci/formats/RandomAccessArray.class loci/formats/TiffTools.class \
-C ../OME-JAVA/src org/openmicroscopy/ds \
-C ../OME-JAVA/src org/openmicroscopy/xml
rm notebook.manifest loci/util/about.txt

cd loci/ome/notebook
ls -l MetadataNotebook.jar
