#!/bin/sh

set -e

list_headers()
{
    for dir in src gen; do
        find "$dir" -name '*.h' | sed -e "s;^$dir/;;"
    done
}

list_headers | while read header; do
    dir="test/headers/$(dirname "$header")"
    test=$(basename "$header")
    test="${test%.h}.cpp"
    mkdir -p "$dir"
    cat <<EOF > "$dir/$test"
#include <$header>

int
main ()
{
  return 0;
}
EOF

    echo "$dir/${test%.cpp}"
done