#!/bin/bash

# bfconvert: a script for converting image files between formats

# Required JARs: loci_tools.jar

# JAR libraries must be in the same directory as this
# command line script for the command to function.

# If you are a developer working from source and have
# the LOCI classes in your CLASSPATH, you can set the
# LOCI_DEVEL environment variable to use them instead.

PROG=loci.formats.tools.ImageConverter
DIR=`dirname "$0"`

if [ $LOCI_DEVEL ]
then
  java -mx512m $PROG "$@"
elif [ -e "$DIR/loci_tools.jar" ] || [ -e "$DIR/bio-formats.jar" ]
then
  java -mx512m \
    -cp "$DIR":"$DIR/bio-formats.jar":"$DIR/loci_tools.jar" $PROG "$@"
else
  echo "Required JAR libraries not found. Please download:"
  echo "  loci_tools.jar"
  echo "from:"
  echo "  http://www.loci.wisc.edu/bio-formats/downloads"
  echo "and place in the same directory as the command line tools."
fi
