#!/usr/bin/env bash

# bfconvert: a script for converting image files between formats

# Required JARs: loci_tools.jar or bioformats_package.jar

BF_DIR=`dirname "$0"`

BF_PROG=loci.formats.tools.ImageConverter "$BF_DIR/bf.sh" "$@"
