#!/bin/bash

# bfconvert: a script for converting image files between formats

# Required JARs: loci_tools.jar

SCIFIO_DIR=`dirname "$0"`

SCIFIO_PROG=loci.formats.tools.ImageConverter "$SCIFIO_DIR/scifio.sh" "$@"
