#!/bin/bash

# bfview: a script for displaying a given image file in the image viewer

# Required JARs: loci_tools.jar

# JAR libraries must be in the same directory as this
# command line script for the command to function.  

# If you are a developer working from source and have
# the LOCI classes in your CLASSPATH, you can set the
# LOCI_DEVEL environment variable to use them instead.

if [ $LOCI_DEVEL ]
then
  java -mx512m loci.formats.ImageViewer "$@"
elif [ -e loci_tools.jar ] || [ -e bio-formats.jar ]
then
  java -mx512m -cp bio-formats.jar:loci_tools.jar loci.formats.ImageViewer "$@"
else
  echo "Required JAR libraries not found. Please download:"
  echo "  loci_tools.jar"
  echo "from:"
  echo "  http://www.loci.wisc.edu/ome/formats.html"
  echo "and place in the same directory as the command line tools."
fi
