#!/bin/bash

# domainlist: a script for listing supported domains in Bio-Formats

# Required JARs: loci_tools.jar

SCIFIO_DIR=`dirname "$0"`

SCIFIO_PROG=loci.formats.tools.PrintDomains "$SCIFIO_DIR/scifio.sh" "$@"
