#!/bin/bash

# domainlist: a script for listing supported domains in Bio-Formats

# Required JARs: loci_tools.jar

# JAR libraries must be in the same directory as this
# command line script for the command to function.

DIR=`dirname "$0"`

PROG=loci.formats.tools.PrintDomains "$DIR/launch.sh" "$@"
