#!/bin/bash

# domainlist: a script for listing supported domains in Bio-Formats

# Required JARs: loci_tools.jar or bioformats_package.jar

BF_DIR=`dirname "$0"`

BF_PROG=loci.formats.tools.PrintDomains "$BF_DIR/bf.sh" "$@"
