#!/bin/bash

# editor: a script for launching the OME Metadata Editor

# Required JARs: loci_tools.jar, ome-editor.jar,
#                ome-java.jar, ome-java-deprecated.jar

# JAR libraries must be in the same directory as this
# command line script for the command to function.

DIR=`dirname "$0"`

source "$DIR/config.sh"

if [ -z "$SCIFIO_DEVEL" ] && \
  ([ ! -e "$DIR/ome-editor.jar" ] || \
  [ ! -e "$DIR/ome-java.jar" ] || \
  [ ! -e "$DIR/ome-java-deprecated.jar" ])
then
  echo "Required JAR libraries not found. Please download:"
  echo "  http://www.loci.wisc.edu/software/daily/ome-editor.jar"
  echo "  http://www.loci.wisc.edu/software/daily/ome-java.jar"
  echo "  http://www.loci.wisc.edu/software/daily/ome-java-deprecated.jar"
  echo "and place in the same directory as the command line tools."
  echo ""
  echo "Please note that the OME Metadata Notebook is legacy software that "
  echo "has been discontinued. Use at your own risk."
else
  PROG=loci.ome.editor.MetadataEditor CPAUX="$DIR/ome-editor.jar:$DIR/ome-java.jar:$DIR/ome-java-deprecated.jar" "$DIR/launch.sh" "$@"
fi
