#!/bin/bash

# editor: a script for launching the OME Metadata Editor

# Please note that the OME Metadata Notebook is legacy software
# that has been discontinued. Use at your own risk.

# Required JARs: loci_tools.jar, ome-editor.jar,
#                ome-java.jar, ome-java-deprecated.jar

SCIFIO_DIR=`dirname "$0"`

source "$SCIFIO_DIR/config.sh"

if [ -z "$SCIFIO_DEVEL" ]
then
  # Developer environment variable unset; add JAR libraries to classpath.
  if [ -e "$SCIFIO_JAR_DIR/ome-editor.jar" -a \
    -e "$SCIFIO_JAR_DIR/ome-java.jar" -a \
    -e "$SCIFIO_JAR_DIR/ome-java-deprecated.jar" ]
  then
    SCIFIO_CP="$SCIFIO_JAR_DIR/ome-editor.jar"
    SCIFIO_CP="$SCIFIO_CP:$SCIFIO_JAR_DIR/ome-java.jar"
    SCIFIO_CP="$SCIFIO_CP:$SCIFIO_JAR_DIR/ome-java-deprecated.jar"
  else
    # Libraries not found; issue an error.
    echo "Required JAR libraries not found. Please download:"
    echo "  http://www.loci.wisc.edu/software/daily/ome-editor.jar"
    echo "  http://www.loci.wisc.edu/software/daily/ome-java.jar"
    echo "  http://www.loci.wisc.edu/software/daily/ome-java-deprecated.jar"
    echo "and place in the same directory as the command line tools."
    echo ""
    exit 3
  fi
fi

SCIFIO_PROG=loci.ome.editor.MetadataEditor \
  SCIFIO_CP="$SCIFIO_CP" "$SCIFIO_DIR/launch.sh" "$@"
