#!/bin/bash

# formatlist: a script for listing supported formats in Bio-Formats

# Required JARs: loci_tools.jar

# JAR libraries must be in the same directory as this
# command line script for the command to function.

# If your CLASSPATH already includes the needed classes,
# you can set the SCIFIO_DEVEL environment variable to
# disable the required JAR library checks.

PROG=loci.formats.tools.PrintFormatTable
DIR=`dirname "$0"`

if [ -n "$SCIFIO_DEVEL" ]
then
  java -mx512m $PROG "$@"
elif [ -e "$DIR/loci_tools.jar" ] || [ -e "$DIR/bio-formats.jar" ]
then
  java -mx512m -cp "$DIR":"$DIR/bio-formats.jar":"$DIR/loci_tools.jar" $PROG "$@"
else
  echo "Required JAR libraries not found. Please download:"
  echo "  loci_tools.jar"
  echo "from:"
  echo "  http://www.loci.wisc.edu/bio-formats/downloads"
  echo "and place in the same directory as the command line tools."
fi
