#!/bin/bash

# ijview: a script for displaying an image file in ImageJ
#         using the Bio-Formats Importer plugin

# Required JARs: loci_tools.jar, ij.jar

SCIFIO_DIR=`dirname "$0"`

source "$SCIFIO_DIR/config.sh"

if [ -z "$SCIFIO_DEVEL" ]
then
  # Developer environment variable unset; add JAR libraries to classpath.
  if [ -e "$SCIFIO_JAR_DIR/ij.jar" ]
  then
    SCIFIO_CP="$SCIFIO_JAR_DIR/ij.jar"
  else
    # Libraries not found; issue an error
    echo "Required JAR libraries not found. Please download:"
    echo "  ij.jar"
    echo "from:"
    echo "  http://imagej.nih.gov/ij/upgrade/"
    echo "and place in the same directory as the command line tools."
    echo ""
    exit 3
  fi
fi

SCIFIO_PROG=loci.plugins.in.Importer \
  SCIFIO_CP="$SCIFIO_CP" "$SCIFIO_DIR/scifio.sh" "$@"
