#!/bin/bash

# fakespw: a script for creating a fake SPW file / directory structure
#          on the file system

# Required JARs: loci_tools.jar

SCIFIO_DIR=`dirname "$0"`

SCIFIO_PROG=loci.formats.tools.ImageFaker "$SCIFIO_DIR/scifio.sh" "$@"
