#!/usr/bin/env bash

# mkfake: a script for creating a fake file / directory structures
#         on the file system

# Required JARs: loci_tools.jar or bioformats_package.jar

BF_DIR=`dirname "$0"`

BF_PROG=loci.formats.tools.ImageFaker "$BF_DIR/bf.sh" "$@"
