#!/bin/bash

# notes: a script for launching OME Notes

# Please note that OME Notes is legacy software
# that has been discontinued. Use at your own risk.

# Required JARs: loci_tools.jar, ome-notes.jar

SCIFIO_DIR=`dirname "$0"`

source "$SCIFIO_DIR/config.sh"

if [ -z "$SCIFIO_DEVEL" ]
then
  # Developer environment variable unset; add JAR libraries to classpath.
  if [ -e "$SCIFIO_JAR_DIR/ome-notes.jar" ]
  then
    SCIFIO_CP="$SCIFIO_JAR_DIR/ome-notes.jar"
  else
    # Libraries not found; issue an error.
    echo "Required JAR libraries not found. Please download:"
    echo "  http://www.loci.wisc.edu/software/daily/ome-notes.jar"
    echo "and place in the same directory as the command line tools."
    echo ""
  fi
fi

SCIFIO_PROG=loci.ome.notes.Notes \
  SCIFIO_CP="$SCIFIO_CP" "$SCIFIO_DIR/launch.sh" "$@"
