#!/bin/bash

# notes: a script for launching OME Notes

# Required JARs: loci_tools.jar, ome-notes.jar

# JAR libraries must be in the same directory as this
# command line script for the command to function.

DIR=`dirname "$0"`

source "$DIR/config.sh"

PROG=loci.ome.notes.Notes

if [ -z "$SCIFIO_DEVEL" ] && [ ! -e "$DIR/ome-notes.jar" ]
then
  echo "Required JAR libraries not found. Please download:"
  echo "  http://www.loci.wisc.edu/software/daily/ome-notes.jar"
  echo "and place in the same directory as the command line tools."
  echo ""
  echo "Please note that OME Notes is legacy software that "
  echo "has been discontinued. Use at your own risk."
else
  PROG=loci.ome.notes.Notes CPAUX="$DIR/ome-notes.jar" "$DIR/launch.sh" "$@"
fi
