#!/bin/bash

# omeul: a command-line client-side import tool for OME

# Required JARs: loci_tools.jar

# JAR libraries must be in the same directory as this
# command line script for the command to function.

DIR=`dirname "$0"`
source "$DIR/config.sh"

PROG=loci.formats.ome.OMEWriter "$DIR/launch.sh" "$@"
