#!/bin/bash

# showinf: a script for displaying information about a given
#          image file, while displaying it in the image viewer

# Required JARs: loci_tools.jar

# JAR libraries must be in the same directory as this
# command line script for the command to function.

DIR=`dirname "$0"`

PROG=loci.formats.tools.ImageInfo "$DIR/launch.sh" "$@"
