#!/bin/sh
# This script is used for testing the build, primarily for use
# with travis, but may be used by hand as well.

set -e
set -x

# Clean up
clean()
{
    mvn clean
}

# Test maven build
maven()
{
    mvn
    clean
}

cpp()
{
    (
        cd cpp
        mkdir build
        cd build
        (
            mkdir gtest
            cd gtest
            cmake /usr/src/gtest
            make
        )
        GTEST_ROOT=$(pwd)/gtest cmake ../..
        make
        make test
        make DESTDIR=../install install
        make doc
    )
}

# Test cppwrap
cppwrap()
{
    (
        maven
        cd components/formats-bsd
        mvn -DskipTests clean package cppwrap:wrap dependency:copy-dependencies
        cd target/cppwrap
        mkdir build
        cd build
        cmake ..
        make
    )
}

# Test sphinx docs build
sphinx()
{
    (
        export SPHINXOPTS="-W"
        cd docs/sphinx
        make clean
        make html
        make latexpdf
    )
}

# Test Ant build targets
antbuild()
{
    (
      ant clean compile
      ant clean compile-autogen
      ant clean compile-formats-api
      ant clean compile-jai
      ant clean compile-formats-common
      ant clean compile-bio-formats-plugins
      ant clean compile-lwf-stubs
      ant clean compile-mdbtools
      ant clean compile-metakit
      ant clean compile-ome-xml
      ant clean compile-ome-poi
      ant clean compile-formats-bsd
      ant clean compile-formats-gpl
      ant clean compile-bio-formats-tools
      ant clean compile-tests
      ant clean compile-turbojpeg
    )
}

for arg in "$@"
do
    case $arg in
        clean)
            clean ;;
        maven)
            maven ;;
        cpp)
            cpp ;;
        cppwrap)
            cppwrap ;;
        sphinx)
            sphinx ;;
        ant)
            antbuild ;;
        all)
            clean && maven && cppwrap && sphinx && antbuild;;
        *)
            echo "Invalid argument: \"$arg\"" >&2
            exit 1
            ;;
    esac
done

exit 0
