#!/bin/bash

# tiffcomment: a script for extracting the comment
#              (OME-XML block or otherwise) from a TIFF file

# Required JARs: loci_tools.jar

# JAR libraries must be in the same directory as this
# command line script for the command to function.

DIR=`dirname "$0"`

PROG=loci.formats.tools.TiffComment "$DIR/launch.sh" "$@"
