#!/usr/bin/env bash

# tiffcomment: a script for extracting the comment
#              (OME-XML block or otherwise) from a TIFF file

# Required JARs: loci_tools.jar or bioformats_package.jar

BF_DIR=`dirname "$0"`

BF_PROG=loci.formats.tools.TiffComment "$BF_DIR/bf.sh" "$@"
