#!/bin/bash

# tiffcomment: a script for extracting the comment
#              (OME-XML block or otherwise) from a TIFF file

# Required JARs: loci_tools.jar

SCIFIO_DIR=`dirname "$0"`

SCIFIO_PROG=loci.formats.tools.TiffComment "$SCIFIO_DIR/scifio.sh" "$@"
