#!/usr/bin/env bash

# xmlindent: a script for prettifying blocks of XML

# Required JARs: loci_tools.jar or bioformats_package.jar

BF_DIR=`dirname "$0"`

BF_PROG=loci.formats.tools.XMLIndent "$BF_DIR/bf.sh" "$@"
