#!/bin/bash

# xmlindent: a script for prettifying blocks of XML

# Required JARs: loci_tools.jar

# JAR libraries must be in the same directory as this
# command line script for the command to function.

SCIFIO_DIR=`dirname "$0"`

SCIFIO_PROG=loci.formats.tools.XMLIndent "$SCIFIO_DIR/launch.sh" "$@"
