#!/bin/bash

# xmlvalid: a script for validating XML files

# Required JARs: loci_tools.jar

# JAR libraries must be in the same directory as this
# command line script for the command to function.

# If you are a developer working from source and have
# the LOCI classes in your CLASSPATH, you can set the
# LOCI_DEVEL environment variable to use them instead.

PROG=loci.formats.tools.XMLValidate
DIR=`dirname "$0"`

# If you are behind a proxy server, the host name and port must be set here.
PROXY_HOST=
PROXY_PORT=

if [ $LOCI_DEVEL ]
then
  java -mx512m -Dhttp.proxyHost=$PROXY_HOST -Dhttp.proxyPort=$PROXY_PORT $PROG "$@"
elif [ -e "$DIR/loci_tools.jar" ] || [ -e "$DIR/bio-formats.jar" ]
then
  java -mx512m -Dhttp.proxyHost=$PROXY_HOST -Dhttp.proxyPort=$PROXY_PORT -cp "$DIR":"$DIR/bio-formats.jar":"$DIR/loci_tools.jar" $PROG "$@"
else
  echo "Required JAR libraries not found. Please download:"
  echo "  loci_tools.jar"
  echo "from:"
  echo "  http://www.openmicroscopy.org/site/products/bio-formats/downloads"
  echo "and place in the same directory as the command line tools."
fi
