#!/bin/bash

# build_plugins: a script for building the LOCI plugins for ImageJ JAR file

cd ..

echo Building loci_plugins.jar...
cp loci/util/about.manifest loci/plugins.config .
echo LOCI plugins for ImageJ > about.txt
echo Built `date` >> about.txt
echo >> about.txt
echo The Bio-Formats library is LOCI software written by >> about.txt
echo Melissa Linkert, Curtis Rueden and Eric Kjellman. >> about.txt
echo http://www.loci.wisc.edu/ome/formats.html >> about.txt
echo >> about.txt
echo The 4D Data Browser is LOCI software written by >> about.txt
echo Francis Wong and Curtis Rueden. >> about.txt
echo 'http://www.loci.wisc.edu/4d/#browser' >> about.txt
echo >> about.txt
echo The OME plugin for ImageJ is LOCI software written by >> about.txt
echo Phil Huettl, Melissa Linkert and Curtis Rueden. >> about.txt
echo http://www.loci.wisc.edu/ome/imagej.html >> about.txt
mv about.txt loci/util/about.txt

jar cfm loci/loci_plugins.jar about.manifest \
plugins.config loci/util/about.txt \
loci/formats/*.class loci/formats/*.txt \
loci/browser/*.class \
loci/ome/*.class \
loci/ome/ij/*.class \
loci/ome/viewer/*.class \
loci/util/*.class \
loci/formats/*.java \
loci/formats/test loci/formats/inf loci/formats/show loci/formats/showinf \
loci/browser/*.java \
loci/ome/*.java \
loci/ome/ij/*.java \
loci/ome/viewer/*.java \
loci/util/*.java

rm about.manifest plugins.config loci/util/about.txt

cd loci
ls -l loci_plugins.jar
