//
// ome-xml.h
//

/*
OME Bio-Formats C++ bindings for native access to Bio-Formats Java library.
Copyright (c) 2008-2010, UW-Madison LOCI.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the UW-Madison LOCI nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY UW-MADISON LOCI ''AS IS'' AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL UW-MADISON LOCI BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/*
IMPORTANT NOTE: Although this software is distributed according to a
"BSD-style" license, it requires the Bio-Formats Java library to do
anything useful, which is licensed under the GPL v2 or later.
As such, if you wish to distribute this software with Bio-Formats itself,
your combined work must be distributed under the terms of the GPL.
*/

/*-----------------------------------------------------------------------------
 *
 * THIS IS AUTOMATICALLY GENERATED CODE.  DO NOT MODIFY.
 * Created by curtis via JaceHeaderAutogen on May 25, 2010 1:08:17 PM CDT
 *
 *-----------------------------------------------------------------------------
 */

#ifndef OME_XML_H
#define OME_XML_H

#include "jace.h"

#include "jace/proxy/ome/xml/About.h"
#include "jace/proxy/ome/xml/CustomNode.h"
#include "jace/proxy/ome/xml/DOMUtil.h"
#include "jace/proxy/ome/xml/MetadataRetrieve.h"
#include "jace/proxy/ome/xml/MetadataStore.h"
#include "jace/proxy/ome/xml/OMEXMLFactory.h"
#include "jace/proxy/ome/xml/OMEXMLMetadataImpl.h"
#include "jace/proxy/ome/xml/OMEXMLNode.h"
//using namespace jace::proxy::ome::xml;

#include "jace/proxy/ome/xml/r2003fc/ome/ArcNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/AuxLightSourceRefNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/ChannelComponentNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/ChannelInfoNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/ChannelSpecTypeNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/ContactNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/DatasetNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/DatasetRefNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/DescriptionNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/DetectorNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/DetectorRefNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/DichroicNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/DisplayOptionsNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/EmFilterNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/ExFilterNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/ExperimentNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/ExperimentRefNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/ExperimenterNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/ExperimenterRefNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/ExperimenterTypeNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/FeatureNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/FilamentNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/FilterNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/FilterRefNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/FilterSetNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/FilterSpecNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/GreyChannelNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/GroupNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/GroupRefNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/ImageNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/ImagingEnvironmentNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/InstrumentNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/InstrumentRefNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/LaserNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/LeaderNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/LightSourceNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/LightSourceRefNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/ManufactSpecNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/MicroscopeNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/OMENode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/OTFNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/OTFRefNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/ObjectiveNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/ObjectiveRefNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/PixelsNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/PlateNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/PlateRefNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/ProjectNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/ProjectRefNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/ProjectionNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/PumpNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/ROINode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/ReferenceNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/ScreenNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/ScreenRefNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/StageLabelNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/ThumbnailNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/TiffDataNode.h"
#include "jace/proxy/ome/xml/r2003fc/ome/TimeNode.h"
//using namespace jace::proxy::ome::xml::r2003fc::ome;

#include "jace/proxy/ome/xml/r200706/SampleTest.h"
//using namespace jace::proxy::ome::xml::r200706;

#include "jace/proxy/ome/xml/r200706/ome/AcquiredPixelsRefNode.h"
#include "jace/proxy/ome/xml/r200706/ome/ArcNode.h"
#include "jace/proxy/ome/xml/r200706/ome/ChannelComponentNode.h"
#include "jace/proxy/ome/xml/r200706/ome/ChannelSpecTypeNode.h"
#include "jace/proxy/ome/xml/r200706/ome/ContactNode.h"
#include "jace/proxy/ome/xml/r200706/ome/DatasetNode.h"
#include "jace/proxy/ome/xml/r200706/ome/DatasetRefNode.h"
#include "jace/proxy/ome/xml/r200706/ome/DescriptionNode.h"
#include "jace/proxy/ome/xml/r200706/ome/DetectorNode.h"
#include "jace/proxy/ome/xml/r200706/ome/DetectorRefNode.h"
#include "jace/proxy/ome/xml/r200706/ome/DichroicNode.h"
#include "jace/proxy/ome/xml/r200706/ome/DisplayOptionsNode.h"
#include "jace/proxy/ome/xml/r200706/ome/ExperimentNode.h"
#include "jace/proxy/ome/xml/r200706/ome/ExperimentRefNode.h"
#include "jace/proxy/ome/xml/r200706/ome/ExperimenterNode.h"
#include "jace/proxy/ome/xml/r200706/ome/ExperimenterRefNode.h"
#include "jace/proxy/ome/xml/r200706/ome/FilamentNode.h"
#include "jace/proxy/ome/xml/r200706/ome/FilterNode.h"
#include "jace/proxy/ome/xml/r200706/ome/FilterSetNode.h"
#include "jace/proxy/ome/xml/r200706/ome/FilterSetRefNode.h"
#include "jace/proxy/ome/xml/r200706/ome/FilterSpecNode.h"
#include "jace/proxy/ome/xml/r200706/ome/GreyChannelNode.h"
#include "jace/proxy/ome/xml/r200706/ome/GroupNode.h"
#include "jace/proxy/ome/xml/r200706/ome/GroupRefNode.h"
#include "jace/proxy/ome/xml/r200706/ome/ImageNode.h"
#include "jace/proxy/ome/xml/r200706/ome/ImagingEnvironmentNode.h"
#include "jace/proxy/ome/xml/r200706/ome/InstrumentNode.h"
#include "jace/proxy/ome/xml/r200706/ome/InstrumentRefNode.h"
#include "jace/proxy/ome/xml/r200706/ome/LaserNode.h"
#include "jace/proxy/ome/xml/r200706/ome/LeaderNode.h"
#include "jace/proxy/ome/xml/r200706/ome/LightSourceNode.h"
#include "jace/proxy/ome/xml/r200706/ome/LightSourceRefNode.h"
#include "jace/proxy/ome/xml/r200706/ome/LogicalChannelNode.h"
#include "jace/proxy/ome/xml/r200706/ome/ManufactSpecNode.h"
#include "jace/proxy/ome/xml/r200706/ome/MicrobeamManipulationNode.h"
#include "jace/proxy/ome/xml/r200706/ome/MicrobeamManipulationRefNode.h"
#include "jace/proxy/ome/xml/r200706/ome/MicroscopeNode.h"
#include "jace/proxy/ome/xml/r200706/ome/OMENode.h"
#include "jace/proxy/ome/xml/r200706/ome/OTFNode.h"
#include "jace/proxy/ome/xml/r200706/ome/OTFRefNode.h"
#include "jace/proxy/ome/xml/r200706/ome/ObjectiveNode.h"
#include "jace/proxy/ome/xml/r200706/ome/ObjectiveRefNode.h"
#include "jace/proxy/ome/xml/r200706/ome/ObjectiveSettingsNode.h"
#include "jace/proxy/ome/xml/r200706/ome/ObjectiveSettingsRefNode.h"
#include "jace/proxy/ome/xml/r200706/ome/PixelsNode.h"
#include "jace/proxy/ome/xml/r200706/ome/PlaneNode.h"
#include "jace/proxy/ome/xml/r200706/ome/PlaneTimingNode.h"
#include "jace/proxy/ome/xml/r200706/ome/ProjectNode.h"
#include "jace/proxy/ome/xml/r200706/ome/ProjectRefNode.h"
#include "jace/proxy/ome/xml/r200706/ome/ProjectionNode.h"
#include "jace/proxy/ome/xml/r200706/ome/PumpNode.h"
#include "jace/proxy/ome/xml/r200706/ome/ROINode.h"
#include "jace/proxy/ome/xml/r200706/ome/ROIRefNode.h"
#include "jace/proxy/ome/xml/r200706/ome/ReferenceNode.h"
#include "jace/proxy/ome/xml/r200706/ome/RegionNode.h"
#include "jace/proxy/ome/xml/r200706/ome/StageLabelNode.h"
#include "jace/proxy/ome/xml/r200706/ome/StagePositionNode.h"
#include "jace/proxy/ome/xml/r200706/ome/ThumbnailNode.h"
#include "jace/proxy/ome/xml/r200706/ome/TiffDataNode.h"
#include "jace/proxy/ome/xml/r200706/ome/TimeNode.h"
#include "jace/proxy/ome/xml/r200706/ome/TransmittanceRangeNode.h"
//using namespace jace::proxy::ome::xml::r200706::ome;

#include "jace/proxy/ome/xml/r200706/spw/ImageRefNode.h"
#include "jace/proxy/ome/xml/r200706/spw/PlateNode.h"
#include "jace/proxy/ome/xml/r200706/spw/PlateRefNode.h"
#include "jace/proxy/ome/xml/r200706/spw/ReagentNode.h"
#include "jace/proxy/ome/xml/r200706/spw/ReagentRefNode.h"
#include "jace/proxy/ome/xml/r200706/spw/ScreenAcquisitionNode.h"
#include "jace/proxy/ome/xml/r200706/spw/ScreenNode.h"
#include "jace/proxy/ome/xml/r200706/spw/ScreenRefNode.h"
#include "jace/proxy/ome/xml/r200706/spw/WellNode.h"
#include "jace/proxy/ome/xml/r200706/spw/WellSampleNode.h"
#include "jace/proxy/ome/xml/r200706/spw/WellSampleRefNode.h"
//using namespace jace::proxy::ome::xml::r200706::spw;

#include "jace/proxy/ome/xml/r200802/ome/ArcNode.h"
#include "jace/proxy/ome/xml/r200802/ome/ChannelComponentNode.h"
#include "jace/proxy/ome/xml/r200802/ome/ChannelSpecTypeNode.h"
#include "jace/proxy/ome/xml/r200802/ome/ContactNode.h"
#include "jace/proxy/ome/xml/r200802/ome/DatasetNode.h"
#include "jace/proxy/ome/xml/r200802/ome/DatasetRefNode.h"
#include "jace/proxy/ome/xml/r200802/ome/DescriptionNode.h"
#include "jace/proxy/ome/xml/r200802/ome/DetectorNode.h"
#include "jace/proxy/ome/xml/r200802/ome/DetectorRefNode.h"
#include "jace/proxy/ome/xml/r200802/ome/DichroicNode.h"
#include "jace/proxy/ome/xml/r200802/ome/DisplayOptionsNode.h"
#include "jace/proxy/ome/xml/r200802/ome/ExperimentNode.h"
#include "jace/proxy/ome/xml/r200802/ome/ExperimentRefNode.h"
#include "jace/proxy/ome/xml/r200802/ome/ExperimenterNode.h"
#include "jace/proxy/ome/xml/r200802/ome/ExperimenterRefNode.h"
#include "jace/proxy/ome/xml/r200802/ome/FilamentNode.h"
#include "jace/proxy/ome/xml/r200802/ome/FilterNode.h"
#include "jace/proxy/ome/xml/r200802/ome/FilterSetNode.h"
#include "jace/proxy/ome/xml/r200802/ome/FilterSetRefNode.h"
#include "jace/proxy/ome/xml/r200802/ome/FilterSpecNode.h"
#include "jace/proxy/ome/xml/r200802/ome/GreyChannelNode.h"
#include "jace/proxy/ome/xml/r200802/ome/GroupNode.h"
#include "jace/proxy/ome/xml/r200802/ome/GroupRefNode.h"
#include "jace/proxy/ome/xml/r200802/ome/ImageNode.h"
#include "jace/proxy/ome/xml/r200802/ome/ImagingEnvironmentNode.h"
#include "jace/proxy/ome/xml/r200802/ome/InstrumentNode.h"
#include "jace/proxy/ome/xml/r200802/ome/InstrumentRefNode.h"
#include "jace/proxy/ome/xml/r200802/ome/LaserNode.h"
#include "jace/proxy/ome/xml/r200802/ome/LeaderNode.h"
#include "jace/proxy/ome/xml/r200802/ome/LightSourceNode.h"
#include "jace/proxy/ome/xml/r200802/ome/LightSourceRefNode.h"
#include "jace/proxy/ome/xml/r200802/ome/LogicalChannelNode.h"
#include "jace/proxy/ome/xml/r200802/ome/ManufactSpecNode.h"
#include "jace/proxy/ome/xml/r200802/ome/MicrobeamManipulationNode.h"
#include "jace/proxy/ome/xml/r200802/ome/MicrobeamManipulationRefNode.h"
#include "jace/proxy/ome/xml/r200802/ome/MicroscopeNode.h"
#include "jace/proxy/ome/xml/r200802/ome/OMENode.h"
#include "jace/proxy/ome/xml/r200802/ome/OTFNode.h"
#include "jace/proxy/ome/xml/r200802/ome/OTFRefNode.h"
#include "jace/proxy/ome/xml/r200802/ome/ObjectiveNode.h"
#include "jace/proxy/ome/xml/r200802/ome/ObjectiveRefNode.h"
#include "jace/proxy/ome/xml/r200802/ome/PixelsNode.h"
#include "jace/proxy/ome/xml/r200802/ome/PlaneNode.h"
#include "jace/proxy/ome/xml/r200802/ome/PlaneTimingNode.h"
#include "jace/proxy/ome/xml/r200802/ome/ProjectNode.h"
#include "jace/proxy/ome/xml/r200802/ome/ProjectRefNode.h"
#include "jace/proxy/ome/xml/r200802/ome/ProjectionNode.h"
#include "jace/proxy/ome/xml/r200802/ome/PumpNode.h"
#include "jace/proxy/ome/xml/r200802/ome/ROINode.h"
#include "jace/proxy/ome/xml/r200802/ome/ROIRefNode.h"
#include "jace/proxy/ome/xml/r200802/ome/ReferenceNode.h"
#include "jace/proxy/ome/xml/r200802/ome/RegionNode.h"
#include "jace/proxy/ome/xml/r200802/ome/StageLabelNode.h"
#include "jace/proxy/ome/xml/r200802/ome/StagePositionNode.h"
#include "jace/proxy/ome/xml/r200802/ome/ThumbnailNode.h"
#include "jace/proxy/ome/xml/r200802/ome/TiffDataNode.h"
#include "jace/proxy/ome/xml/r200802/ome/TimeNode.h"
#include "jace/proxy/ome/xml/r200802/ome/TransmittanceRangeNode.h"
#include "jace/proxy/ome/xml/r200802/ome/UUIDNode.h"
//using namespace jace::proxy::ome::xml::r200802::ome;

#include "jace/proxy/ome/xml/r200802/spw/ImageRefNode.h"
#include "jace/proxy/ome/xml/r200802/spw/PlateNode.h"
#include "jace/proxy/ome/xml/r200802/spw/PlateRefNode.h"
#include "jace/proxy/ome/xml/r200802/spw/ReagentNode.h"
#include "jace/proxy/ome/xml/r200802/spw/ReagentRefNode.h"
#include "jace/proxy/ome/xml/r200802/spw/ScreenAcquisitionNode.h"
#include "jace/proxy/ome/xml/r200802/spw/ScreenNode.h"
#include "jace/proxy/ome/xml/r200802/spw/ScreenRefNode.h"
#include "jace/proxy/ome/xml/r200802/spw/WellNode.h"
#include "jace/proxy/ome/xml/r200802/spw/WellSampleNode.h"
#include "jace/proxy/ome/xml/r200802/spw/WellSampleRefNode.h"
//using namespace jace::proxy::ome::xml::r200802::spw;

#include "jace/proxy/ome/xml/r200809/ome/ArcNode.h"
#include "jace/proxy/ome/xml/r200809/ome/BasicSvgShapeNode.h"
#include "jace/proxy/ome/xml/r200809/ome/ChannelComponentNode.h"
#include "jace/proxy/ome/xml/r200809/ome/ChannelSpecTypeNode.h"
#include "jace/proxy/ome/xml/r200809/ome/ChannelsNode.h"
#include "jace/proxy/ome/xml/r200809/ome/CircleNode.h"
#include "jace/proxy/ome/xml/r200809/ome/ContactNode.h"
#include "jace/proxy/ome/xml/r200809/ome/DatasetNode.h"
#include "jace/proxy/ome/xml/r200809/ome/DatasetRefNode.h"
#include "jace/proxy/ome/xml/r200809/ome/DescriptionNode.h"
#include "jace/proxy/ome/xml/r200809/ome/DetectorNode.h"
#include "jace/proxy/ome/xml/r200809/ome/DetectorRefNode.h"
#include "jace/proxy/ome/xml/r200809/ome/DichroicNode.h"
#include "jace/proxy/ome/xml/r200809/ome/DisplayOptionsNode.h"
#include "jace/proxy/ome/xml/r200809/ome/EllipseNode.h"
#include "jace/proxy/ome/xml/r200809/ome/ExperimentNode.h"
#include "jace/proxy/ome/xml/r200809/ome/ExperimentRefNode.h"
#include "jace/proxy/ome/xml/r200809/ome/ExperimenterNode.h"
#include "jace/proxy/ome/xml/r200809/ome/ExperimenterRefNode.h"
#include "jace/proxy/ome/xml/r200809/ome/FilamentNode.h"
#include "jace/proxy/ome/xml/r200809/ome/FilterNode.h"
#include "jace/proxy/ome/xml/r200809/ome/FilterSetNode.h"
#include "jace/proxy/ome/xml/r200809/ome/FilterSetRefNode.h"
#include "jace/proxy/ome/xml/r200809/ome/FilterSpecNode.h"
#include "jace/proxy/ome/xml/r200809/ome/GreyChannelNode.h"
#include "jace/proxy/ome/xml/r200809/ome/GroupNode.h"
#include "jace/proxy/ome/xml/r200809/ome/GroupRefNode.h"
#include "jace/proxy/ome/xml/r200809/ome/ImageNode.h"
#include "jace/proxy/ome/xml/r200809/ome/ImagingEnvironmentNode.h"
#include "jace/proxy/ome/xml/r200809/ome/InstrumentNode.h"
#include "jace/proxy/ome/xml/r200809/ome/InstrumentRefNode.h"
#include "jace/proxy/ome/xml/r200809/ome/LaserNode.h"
#include "jace/proxy/ome/xml/r200809/ome/LeaderNode.h"
#include "jace/proxy/ome/xml/r200809/ome/LightEmittingDiodeNode.h"
#include "jace/proxy/ome/xml/r200809/ome/LightSourceNode.h"
#include "jace/proxy/ome/xml/r200809/ome/LightSourceRefNode.h"
#include "jace/proxy/ome/xml/r200809/ome/LineNode.h"
#include "jace/proxy/ome/xml/r200809/ome/LogicalChannelNode.h"
#include "jace/proxy/ome/xml/r200809/ome/LogicalChannelRefNode.h"
#include "jace/proxy/ome/xml/r200809/ome/ManufactSpecNode.h"
#include "jace/proxy/ome/xml/r200809/ome/MaskNode.h"
#include "jace/proxy/ome/xml/r200809/ome/MaskPixelsNode.h"
#include "jace/proxy/ome/xml/r200809/ome/MicrobeamManipulationNode.h"
#include "jace/proxy/ome/xml/r200809/ome/MicrobeamManipulationRefNode.h"
#include "jace/proxy/ome/xml/r200809/ome/MicroscopeNode.h"
#include "jace/proxy/ome/xml/r200809/ome/OMENode.h"
#include "jace/proxy/ome/xml/r200809/ome/OTFNode.h"
#include "jace/proxy/ome/xml/r200809/ome/OTFRefNode.h"
#include "jace/proxy/ome/xml/r200809/ome/ObjectiveNode.h"
#include "jace/proxy/ome/xml/r200809/ome/ObjectiveRefNode.h"
#include "jace/proxy/ome/xml/r200809/ome/PixelsNode.h"
#include "jace/proxy/ome/xml/r200809/ome/PlaneNode.h"
#include "jace/proxy/ome/xml/r200809/ome/PlaneTimingNode.h"
#include "jace/proxy/ome/xml/r200809/ome/PointNode.h"
#include "jace/proxy/ome/xml/r200809/ome/PolygonNode.h"
#include "jace/proxy/ome/xml/r200809/ome/PolylineNode.h"
#include "jace/proxy/ome/xml/r200809/ome/ProjectNode.h"
#include "jace/proxy/ome/xml/r200809/ome/ProjectRefNode.h"
#include "jace/proxy/ome/xml/r200809/ome/ProjectionNode.h"
#include "jace/proxy/ome/xml/r200809/ome/PumpNode.h"
#include "jace/proxy/ome/xml/r200809/ome/ROINode.h"
#include "jace/proxy/ome/xml/r200809/ome/ROIRefNode.h"
#include "jace/proxy/ome/xml/r200809/ome/RectNode.h"
#include "jace/proxy/ome/xml/r200809/ome/ReferenceNode.h"
#include "jace/proxy/ome/xml/r200809/ome/RegionNode.h"
#include "jace/proxy/ome/xml/r200809/ome/ShapeNode.h"
#include "jace/proxy/ome/xml/r200809/ome/StageLabelNode.h"
#include "jace/proxy/ome/xml/r200809/ome/StagePositionNode.h"
#include "jace/proxy/ome/xml/r200809/ome/ThumbnailNode.h"
#include "jace/proxy/ome/xml/r200809/ome/TiffDataNode.h"
#include "jace/proxy/ome/xml/r200809/ome/TimeNode.h"
#include "jace/proxy/ome/xml/r200809/ome/TransmittanceRangeNode.h"
#include "jace/proxy/ome/xml/r200809/ome/UUIDNode.h"
#include "jace/proxy/ome/xml/r200809/ome/UnionNode.h"
//using namespace jace::proxy::ome::xml::r200809::ome;

#include "jace/proxy/ome/xml/r200809/spw/ImageRefNode.h"
#include "jace/proxy/ome/xml/r200809/spw/PlateNode.h"
#include "jace/proxy/ome/xml/r200809/spw/PlateRefNode.h"
#include "jace/proxy/ome/xml/r200809/spw/ReagentNode.h"
#include "jace/proxy/ome/xml/r200809/spw/ReagentRefNode.h"
#include "jace/proxy/ome/xml/r200809/spw/ScreenAcquisitionNode.h"
#include "jace/proxy/ome/xml/r200809/spw/ScreenNode.h"
#include "jace/proxy/ome/xml/r200809/spw/ScreenRefNode.h"
#include "jace/proxy/ome/xml/r200809/spw/WellNode.h"
#include "jace/proxy/ome/xml/r200809/spw/WellSampleNode.h"
#include "jace/proxy/ome/xml/r200809/spw/WellSampleRefNode.h"
//using namespace jace::proxy::ome::xml::r200809::spw;

#include "jace/proxy/ome/xml/r201004/AbstractOMEModelObject.h"
#include "jace/proxy/ome/xml/r201004/Annotation.h"
#include "jace/proxy/ome/xml/r201004/AnnotationRef.h"
#include "jace/proxy/ome/xml/r201004/Arc.h"
#include "jace/proxy/ome/xml/r201004/BinData.h"
#include "jace/proxy/ome/xml/r201004/BinaryFile.h"
#include "jace/proxy/ome/xml/r201004/BooleanAnnotation.h"
#include "jace/proxy/ome/xml/r201004/Channel.h"
#include "jace/proxy/ome/xml/r201004/ChannelRef.h"
#include "jace/proxy/ome/xml/r201004/Contact.h"
#include "jace/proxy/ome/xml/r201004/Dataset.h"
#include "jace/proxy/ome/xml/r201004/DatasetRef.h"
#include "jace/proxy/ome/xml/r201004/Detector.h"
#include "jace/proxy/ome/xml/r201004/DetectorSettings.h"
#include "jace/proxy/ome/xml/r201004/Dichroic.h"
#include "jace/proxy/ome/xml/r201004/DichroicRef.h"
#include "jace/proxy/ome/xml/r201004/DoubleAnnotation.h"
#include "jace/proxy/ome/xml/r201004/Ellipse.h"
#include "jace/proxy/ome/xml/r201004/EmissionFilterRef.h"
#include "jace/proxy/ome/xml/r201004/ExcitationFilterRef.h"
#include "jace/proxy/ome/xml/r201004/Experiment.h"
#include "jace/proxy/ome/xml/r201004/ExperimentRef.h"
#include "jace/proxy/ome/xml/r201004/Experimenter.h"
#include "jace/proxy/ome/xml/r201004/ExperimenterRef.h"
#include "jace/proxy/ome/xml/r201004/External.h"
#include "jace/proxy/ome/xml/r201004/Filament.h"
#include "jace/proxy/ome/xml/r201004/FileAnnotation.h"
#include "jace/proxy/ome/xml/r201004/Filter.h"
#include "jace/proxy/ome/xml/r201004/FilterRef.h"
#include "jace/proxy/ome/xml/r201004/FilterSet.h"
#include "jace/proxy/ome/xml/r201004/FilterSetRef.h"
#include "jace/proxy/ome/xml/r201004/Group.h"
#include "jace/proxy/ome/xml/r201004/GroupRef.h"
#include "jace/proxy/ome/xml/r201004/Image.h"
#include "jace/proxy/ome/xml/r201004/ImageRef.h"
#include "jace/proxy/ome/xml/r201004/ImagingEnvironment.h"
#include "jace/proxy/ome/xml/r201004/Instrument.h"
#include "jace/proxy/ome/xml/r201004/InstrumentRef.h"
#include "jace/proxy/ome/xml/r201004/Laser.h"
#include "jace/proxy/ome/xml/r201004/Leader.h"
#include "jace/proxy/ome/xml/r201004/LightEmittingDiode.h"
#include "jace/proxy/ome/xml/r201004/LightPath.h"
#include "jace/proxy/ome/xml/r201004/LightSource.h"
#include "jace/proxy/ome/xml/r201004/LightSourceSettings.h"
#include "jace/proxy/ome/xml/r201004/Line.h"
#include "jace/proxy/ome/xml/r201004/ListAnnotation.h"
#include "jace/proxy/ome/xml/r201004/LongAnnotation.h"
#include "jace/proxy/ome/xml/r201004/ManufacturerSpec.h"
#include "jace/proxy/ome/xml/r201004/Mask.h"
#include "jace/proxy/ome/xml/r201004/MetadataOnly.h"
#include "jace/proxy/ome/xml/r201004/MicrobeamManipulation.h"
#include "jace/proxy/ome/xml/r201004/MicrobeamManipulationRef.h"
#include "jace/proxy/ome/xml/r201004/Microscope.h"
#include "jace/proxy/ome/xml/r201004/OME.h"
#include "jace/proxy/ome/xml/r201004/OMEModel.h"
#include "jace/proxy/ome/xml/r201004/OMEModelImpl.h"
#include "jace/proxy/ome/xml/r201004/OMEModelObject.h"
#include "jace/proxy/ome/xml/r201004/OTF.h"
#include "jace/proxy/ome/xml/r201004/OTFRef.h"
#include "jace/proxy/ome/xml/r201004/Objective.h"
#include "jace/proxy/ome/xml/r201004/ObjectiveSettings.h"
#include "jace/proxy/ome/xml/r201004/Path.h"
#include "jace/proxy/ome/xml/r201004/Pixels.h"
#include "jace/proxy/ome/xml/r201004/Plane.h"
#include "jace/proxy/ome/xml/r201004/Plate.h"
#include "jace/proxy/ome/xml/r201004/PlateAcquisition.h"
#include "jace/proxy/ome/xml/r201004/PlateRef.h"
#include "jace/proxy/ome/xml/r201004/Point.h"
#include "jace/proxy/ome/xml/r201004/Polyline.h"
#include "jace/proxy/ome/xml/r201004/Project.h"
#include "jace/proxy/ome/xml/r201004/ProjectRef.h"
#include "jace/proxy/ome/xml/r201004/Pump.h"
#include "jace/proxy/ome/xml/r201004/ROI.h"
#include "jace/proxy/ome/xml/r201004/ROIRef.h"
#include "jace/proxy/ome/xml/r201004/Reagent.h"
#include "jace/proxy/ome/xml/r201004/ReagentRef.h"
#include "jace/proxy/ome/xml/r201004/Rectangle.h"
#include "jace/proxy/ome/xml/r201004/Reference.h"
#include "jace/proxy/ome/xml/r201004/Screen.h"
#include "jace/proxy/ome/xml/r201004/ScreenRef.h"
#include "jace/proxy/ome/xml/r201004/Settings.h"
#include "jace/proxy/ome/xml/r201004/Shape.h"
#include "jace/proxy/ome/xml/r201004/StageLabel.h"
#include "jace/proxy/ome/xml/r201004/StringAnnotation.h"
#include "jace/proxy/ome/xml/r201004/StructuredAnnotations.h"
#include "jace/proxy/ome/xml/r201004/Text.h"
#include "jace/proxy/ome/xml/r201004/TiffData.h"
#include "jace/proxy/ome/xml/r201004/TimestampAnnotation.h"
#include "jace/proxy/ome/xml/r201004/TransmittanceRange.h"
#include "jace/proxy/ome/xml/r201004/UUID.h"
#include "jace/proxy/ome/xml/r201004/Union.h"
#include "jace/proxy/ome/xml/r201004/Well.h"
#include "jace/proxy/ome/xml/r201004/WellSample.h"
#include "jace/proxy/ome/xml/r201004/WellSampleRef.h"
#include "jace/proxy/ome/xml/r201004/XMLAnnotation.h"
//using namespace jace::proxy::ome::xml::r201004;

#include "jace/proxy/ome/xml/r201004/enums/AcquisitionMode.h"
#include "jace/proxy/ome/xml/r201004/enums/ArcType.h"
#include "jace/proxy/ome/xml/r201004/enums/Binning.h"
#include "jace/proxy/ome/xml/r201004/enums/Compression.h"
#include "jace/proxy/ome/xml/r201004/enums/ContrastMethod.h"
#include "jace/proxy/ome/xml/r201004/enums/Correction.h"
#include "jace/proxy/ome/xml/r201004/enums/DetectorType.h"
#include "jace/proxy/ome/xml/r201004/enums/DimensionOrder.h"
#include "jace/proxy/ome/xml/r201004/enums/Enumeration.h"
#include "jace/proxy/ome/xml/r201004/enums/EnumerationException.h"
#include "jace/proxy/ome/xml/r201004/enums/ExperimentType.h"
#include "jace/proxy/ome/xml/r201004/enums/FilamentType.h"
#include "jace/proxy/ome/xml/r201004/enums/FillRule.h"
#include "jace/proxy/ome/xml/r201004/enums/FilterType.h"
#include "jace/proxy/ome/xml/r201004/enums/FontFamily.h"
#include "jace/proxy/ome/xml/r201004/enums/FontStyle.h"
#include "jace/proxy/ome/xml/r201004/enums/IlluminationType.h"
#include "jace/proxy/ome/xml/r201004/enums/Immersion.h"
#include "jace/proxy/ome/xml/r201004/enums/LaserMedium.h"
#include "jace/proxy/ome/xml/r201004/enums/LaserType.h"
#include "jace/proxy/ome/xml/r201004/enums/LineCap.h"
#include "jace/proxy/ome/xml/r201004/enums/Marker.h"
#include "jace/proxy/ome/xml/r201004/enums/Medium.h"
#include "jace/proxy/ome/xml/r201004/enums/MicrobeamManipulationType.h"
#include "jace/proxy/ome/xml/r201004/enums/MicroscopeType.h"
#include "jace/proxy/ome/xml/r201004/enums/NamingConvention.h"
#include "jace/proxy/ome/xml/r201004/enums/PixelType.h"
#include "jace/proxy/ome/xml/r201004/enums/ProfileSource.h"
#include "jace/proxy/ome/xml/r201004/enums/Pulse.h"
//using namespace jace::proxy::ome::xml::r201004::enums;

#include "jace/proxy/ome/xml/r201004/enums/handlers/AcquisitionModeEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/ArcTypeEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/BinningEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/CompressionEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/ContrastMethodEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/CorrectionEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/DetectorTypeEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/DimensionOrderEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/ExperimentTypeEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/FilamentTypeEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/FillRuleEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/FilterTypeEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/FontFamilyEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/FontStyleEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/IEnumerationHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/IlluminationTypeEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/ImmersionEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/LaserMediumEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/LaserTypeEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/LineCapEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/MarkerEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/MediumEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/MicrobeamManipulationTypeEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/MicroscopeTypeEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/NamingConventionEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/PixelTypeEnumHandler.h"
#include "jace/proxy/ome/xml/r201004/enums/handlers/PulseEnumHandler.h"
//using namespace jace::proxy::ome::xml::r201004::enums::handlers;

#include "jace/proxy/ome/xml/r201004/primitives/NonNegativeInteger.h"
#include "jace/proxy/ome/xml/r201004/primitives/PercentFraction.h"
#include "jace/proxy/ome/xml/r201004/primitives/PositiveInteger.h"
#include "jace/proxy/ome/xml/r201004/primitives/PrimitiveType.h"
//using namespace jace::proxy::ome::xml::r201004::primitives;

#endif
